version: "3.8"

services:
  postgres:
    container_name: telegram_bot
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: telegram_bot_db
    ports:
      - "5432:5432"
    restart: unless-stopped

