spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/telegram_bot_db}
    username: ${JDBC_DATABASE_USERNAME postgres}
    password: ${JDBC_DATABASE_PASSWORD postgres}
  jpa:
    hibernate:
     ddl-auto: validate
    show-sql: false
    generate-ddl: false
logging:
  level:
    root: error