bot:
  name: MyMortyCat_bot
  token: 5214743430:AAH_jBaZtysWLE7wA4sYj98_TbPykr-7XSE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_bot_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
     ddl-auto: validate
    show-sql: false
    generate-ddl: false