bot:
  name: MyCatBotTest
  token: 5261680729:AAFA0StFi-3g92ZoEIJvLFlH-t6lYxz1iwI
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_bot_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
     ddl-auto: validate
    show-sql: true
    generate-ddl: true
  flyway:
    enabled: false
logging:
  level:
    root: error