bot:
  name: MyCatBot
  token: 5261680729:AAFA0StFi-3g92ZoEIJvLFlH-t6lYxz1iwI
spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
     ddl-auto: validate
    show-sql: true
    generate-ddl: false
  flyway:
    enabled: true
logging:
  level:
    root: error